students/urls.py
"""Defines URL patterns for students."""
from django.urls import path
from students.views import students_view, groups_view, journal_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
    # Students pages
    path('', students_view.students_list, name='home'),
    path('students/add/', students_view.students_add, name='students_add'),
    path('students/<int:student_id>/edit/', students_view.students_edit, name='students_edit'),
    path('students/<int:student_id>/delete/', students_view.students_delete, name='students_delete'),
    # Groups pages
    path('groups/', groups_view.groups_list, name='groups'),
    path('groups/add/', groups_view.groups_add, name='groups_add'),
    path('groups/<int:group_id>/edit/', groups_view.groups_edit, name='groups_edit'),
    path('groups/<int:group_id>/delete/', groups_view.groups_delete, name='groups_delete'),
    # Journal pages
    path('journal/', journal_view.journal_list, name='journal')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
]

students/models.py
from django.db import models


class Student(models.Model):
    """Student Model"""
    first_name = models.CharField(
        max_length=256, blank=False, verbose_name="Імʼя"
    )
    last_name = models.CharField(
        max_length=256, blank=False, verbose_name="Прізвище"
    )
    middle_name = models.CharField(
        max_length=256, blank=True, verbose_name="По-батькові", default=''
    )
    birthday = models.DateField(
        blank=False, verbose_name="Дата народження", null=True
    )
    photo = models.ImageField(
        blank=True, verbose_name="Фото", null=True
    )
    ticket = models.CharField(
        max_length=256, blank=False, verbose_name="Білет"
    )
    student_group = models.ForeignKey(
        'Group', verbose_name="Група", blank=False, null=True, on_delete=models.PROTECT
    )
    notes = models.TextField(
        blank=True, verbose_name="Додаткові нотатки"
    )

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенти"

    def __str__(self):
        """Return first_name last_name"""
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()


class Group(models.Model):
    """Group Model"""
    title = models.CharField(
        max_length=256, verbose_name="Назва"
    )
    leader = models.OneToOneField(
        'Student', verbose_name="Староста", blank=True, null=True, on_delete=models.SET_NULL
    )
    notes = models.TextField(
        blank=True, verbose_name="Додаткові нотатки"
    )

    class Meta:
        verbose_name = "Група"
        verbose_name_plural = "Групи"

    def __str__(self):
        if self.leader:
            return f"{self.title} ({self.leader.first_name}{self.leader.last_name})"
        else:
            return f"{self.title}"

students/models/groups_model.py
from django.db import models


class Group(models.Model):
    """Group Model"""
    title = models.CharField(
        max_length=256, verbose_name="Назва"
    )
    leader = models.OneToOneField(
        'Student', verbose_name="Староста", blank=True, null=True, on_delete=models.SET_NULL
    )
    notes = models.TextField(
        blank=True, verbose_name="Додаткові нотатки"
    )

    class Meta:
        verbose_name = "Група"
        verbose_name_plural = "Групи"

    def __str__(self):
        if self.leader:
            return f"{self.title} ({self.leader.first_name}{self.leader.last_name})"
        else:
            return f"{self.title}"

students/models/students_model.py
from django.db import models


class Student(models.Model):
    """Student Model"""
    first_name = models.CharField(
        max_length=256, blank=False, verbose_name="Імʼя"
    )
    last_name = models.CharField(
        max_length=256, blank=False, verbose_name="Прізвище"
    )
    middle_name = models.CharField(
        max_length=256, blank=True, verbose_name="По-батькові", default=''
    )
    birthday = models.DateField(
        blank=False, verbose_name="Дата народження", null=True
    )
    photo = models.ImageField(
        blank=True, verbose_name="Фото", null=True
    )
    ticket = models.CharField(
        max_length=256, blank=False, verbose_name="Білет"
    )
    student_group = models.ForeignKey(
        'Group', verbose_name="Група", blank=False, null=True, on_delete=models.PROTECT
    )
    notes = models.TextField(
        blank=True, verbose_name="Додаткові нотатки"
    )

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенти"

    def __str__(self):
        """Return first_name last_name"""
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()

students/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Views for Students
def students_list(request):
    students = (
        {'id': 1,
         'first_name': 'Мейсон',
         'last_name': 'Пайнс',
         'ticket': 215,
         'image': 'img/gravity_falls_na_avu01.jpg'},
        {'id': 2,
         'first_name': 'Мейбл',
         'last_name': 'Пайнс',
         'ticket': 152,
         'image': 'img/gravity_falls_na_avu02.jpg'},
        {'id': 3,
         'first_name': 'Стенлі',
         'last_name': 'Пайнс',
         'ticket': 64,
         'image': 'img/gravity_falls_na_avu03.jpg'}
    )
    return render(request, 'students/students_list.html', {'students': students})


def students_add(request):
    return HttpResponse('<h1>Student Add Form</h1>')


def students_edit(request, student_id):
    return HttpResponse('<h1>Student Edit %s</h1>' % student_id)


def students_delete(request, student_id):
    return HttpResponse('<h1>Student Delete %s</h1>' % student_id)


# Views for Groups
def groups_list(request):
    groups = (
        {'id': 1,
         'name': 'ME-1',
         'leader': {'id': 1, 'name': 'Мейсон Пайнс'}},
        {'id': 2,
         'name': 'ME-2',
         'leader': {'id': 2, 'name': 'Майбл Пайнс'}},
        {'id': 3,
         'name': 'ME-3',
         'leader': {'id': 3, 'name': 'Стенлі Пайнс'}},
    )
    return render(request, 'students/groups_list.html', {'groups': groups})


def groups_add(request):
    return HttpResponse('<h1>Group Add Form</h1>')


def groups_edit(request, group_id):
    return HttpResponse('<h1>Group Edit %s</h1>' % group_id)


def groups_delete(request, group_id):
    return HttpResponse('<h1>Group Delete %s</h1>' % group_id)

students/views/groups_view.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from students.models.groups_model import Group


def groups_list(request):
    groups = Group.objects.all()

    order_by = request.GET.get('order_by')
    if order_by in ('id', 'title', 'leader'):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse') == '1':
            groups = groups.reverse()

    paginator = Paginator(groups, 3)
    page_number = request.GET.get('page')
    groups = paginator.get_page(page_number)
    return render(request, 'students/groups_list.html', {'groups': groups})


def groups_add(request):
    return HttpResponse('<h1>Group Add Form</h1>')


def groups_edit(request, group_id):
    return HttpResponse('<h1>Group Edit %s</h1>' % group_id)


def groups_delete(request, group_id):
    return HttpResponse('<h1>Group Delete %s</h1>' % group_id)

students/views/journal_view.py
from django.http import HttpResponse
from django.shortcuts import render


def journal_list(request):
    journals = (
        {'student': {'id': 1, 'name': 'Мейсон Пайнс'}},
        {'student': {'id': 2, 'name': 'Майбл Пайнс'}},
        {'student': {'id': 3, 'name': 'Стенлі Пайнс'}}
    )
    return render(request, 'students/journal_list.html', {'journals': journals})

students/views/students_view.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from students.models.groups_model import Group
from students.models.students_model import Student

from datetime import datetime
import imghdr
import os.path

def students_list(request):
    students = Student.objects.all()

    # try to order student list
    order_by = request.GET.get('order_by')
    if order_by in ('id', 'last_name', 'first_name', 'ticket'):
        students = students.order_by(order_by)
        if request.GET.get('reverse') == '1':
            students = students.reverse()

    # paginator students
    paginator = Paginator(students, 3)
    page_number = request.GET.get('page')
    students = paginator.get_page(page_number)
    return render(request, 'students/students_list.html', {'students': students})


def students_add(request):
    # if form was POST
    if request.method == "POST":

        # if form ADD button clicked
        if request.POST.get('add_button') is not None:
            # errors collection
            errors = {}
            # data collection
            data = {'middle_name': request.POST.get('middle_name'),
                    'notes': request.POST.get('notes')}

            # validate user input
            first_name = request.POST.get('first_name', '').strip()
            if not first_name:
                errors['first_name'] = "Імʼя є обовʼязковим"
            else:
                data['first_name'] = first_name

            last_name = request.POST.get('last_name', '').strip()
            if not last_name:
                errors['last_name'] = "Прізвище є обовʼязковим"
            else:
                data['last_name'] = last_name

            birthday = request.POST.get('birthday', '').strip()
            if not birthday:
                errors['birthday'] = "Дата народження є обовʼязковим"
            else:
                try:
                    datetime.strptime(birthday, '%Y-%m-%d')
                except Exception:
                    errors['birthday'] = "Введіть коректний формат дати (напр. 1984-12-30)"
                else:
                    data['birthday'] = birthday

            ticket = request.POST.get('ticket', '').strip()
            if not ticket:
                errors['ticket'] = "Номер білета є обовʼязковим"
            else:
                data['ticket'] = ticket

            student_group = request.POST.get('student_group', '').strip()
            if not student_group:
                errors['student_group'] = "Оберіть групу для студента"
            else:
                group = Group.objects.filter(pk=student_group).first()
                if group:
                    data['student_group'] = group
                else:
                    errors['student_group'] = "Оберіть коректну групу"

            photo = request.FILES.get('photo')
            if photo:
                if photo.content_type == ("image/jpeg" or "image/png"):
                    if photo.size < 2097152:
                        data['photo'] = photo
                    else:
                        bt_to_mb = round(photo.size/1024.0**2, 2)
                        errors['photo'] = f"Розмір фото {bt_to_mb}мб, а повинно бути меньше 2мб"
                else:
                    errors['photo'] = "Фото повинно бути .jpg або .png"

            # create student object and save it to database
            if not errors:
                student = Student(**data)
                student.save()
                # redirect user to students list
                messages.success(request, "Студента успішно додано!")
                return HttpResponseRedirect(reverse('students:home'))
            # render form with errors and previous user input
            else:
                messages.error(request, "Будь ласка, виправте помилки!")
                return render(request, 'students/students_add.html',
                              {'groups': Group.objects.all().order_by('title'), 'errors': errors})

        # if form CANCEL button clicked
        elif request.POST.get('cancel_button') is not None:
            # redirect user to students list
            messages.info(request, "Додавання студента скасовано!")
            return HttpResponseRedirect(reverse('students:home'))

    else:
        # initial form render
        return render(request, 'students/students_add.html',
                      {'groups': Group.objects.all().order_by('title')})


def students_edit(request, student_id):
    return HttpResponse('<h1>Student Edit %s</h1>' % student_id)


def students_delete(request, student_id):
    return HttpResponse('<h1>Student Delete %s</h1>' % student_id)

students/templates/students/base.html
{% load static %}

<!DOCTYPE html>
<html lang="uk">

<head>
  <meta charset="UTF-8"/>
  <title>Сервіс Обліку Студентів - {% block meta_title %}{% endblock meta_title %}</title>
  <meta name="description"
        content="Система Обліку Студентів Навчального Закладу"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>

  <!-- Include Styles -->
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
        crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block extra_css %}{% endblock extra_css %}
</head>

<body>
<!-- Start Container -->
<div class="container">

  <!-- Start Header -->
  <div class="row mt-3" id="header">
    <!-- Logo -->
    <div class="col-sm-8">
      <h1>Сервіс Обліку Студентів</h1>
    </div>
    <!-- Groups Selector -->
    <div class="col-sm-4 d-flex" id="group-selector">
      <label for="group"><strong>Група:</strong></label>
      <select class="custom-select" name="group" id="group">
        <option selected>Усі Студенти</option>
        <option value="">One</option>
        <option value="">Two</option>
        <option value="">Three</option>
      </select>
    </div>
  </div>
  <!-- End Header -->

  <!-- Start SubHeader -->
  <div class="row" id="sub-header">
    <div class="col-sm-12">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          {% url 'students:home' as home_url %}
          <a class="nav-link {% if request.path == home_url %}active{% endif %}"
             href="{{ home_url }}">Студенти</a>
        </li>
        <li class="nav-item">
          {% url 'students:journal' as journal_url %}
          <a class="nav-link {% if request.path == journal_url %}active{% endif %}"
             href="{{ journal_url }}">Відвідування</a>
        </li>
        <li class="nav-item">
          {% url 'students:groups' as groups_url %}
          <a class="nav-link {% if request.path == groups_url %}active{% endif %}"
             href="{{ groups_url }}">Групи</a>
        </li>
      </ul>
    </div>
  </div>
  <!-- End SubHeader -->

  <!-- Start Content Column-->
  <div class="row" id="content-columns">
    <div class="col-sm-12" id="content-column">
      <!-- Status Message -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}

      <div class="d-flex my-3">
        <h2>
          {% block title %}{% endblock title %}
        </h2>

        {% block button %}{% endblock button %}
      </div>

      {% block content %}{% endblock content %}
    </div>
  </div>
  <!-- End Content Column-->

  <!-- Start Footer -->
  <div class="row" id="footer">
    <div class="col-sm-12">
      &copy; 2021 Сервіс Обліку Студентів
    </div>
  </div>
  <!-- End Footer -->

</div>
<!-- End Container -->

<!-- Javascript Section -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>

students/templates/students/groups_list.html
{% extends "students/base.html" %}
{% load static %}

{% block meta_title %}Групи{% endblock meta_title %}

{% block title %}Список Груп{% endblock title %}

{% block button %}
<div class="ml-3">
  <a class="btn btn-primary" href="{% url 'students:groups_add' %}" role="button">Додати Групу</a>
</div>
{% endblock button %}

{% block content %}
<!-- Start Groups List -->
<table class="table table-hover table-striped">
  {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
  <thead>
  <tr>
    <th>
      <a href="?order_by=id{% if order_by == 'id' and reverse != '1' %}&reverse=1{% endif %}">
        №
        {% if order_by == 'id' and reverse != '1' %}&uarr;
        {% elif order_by == 'id' and reverse == '1' %}&darr;
        {% endif %}
      </a>
    </th>
    <th>
      <a href="?order_by=title{% if order_by == 'title' and reverse != '1' %}&reverse=1{% endif %}">
        Назва
        {% if order_by == 'title' and reverse != '1' %}&uarr;
        {% elif order_by == 'title' and reverse == '1' %}&darr;
        {% endif %}
      </a>
    </th>
    <th>
      <a href="?order_by=leader{% if order_by == 'leader' and reverse != '1' %}&reverse=1{% endif %}">
        Староста
        {% if order_by == 'leader' and reverse != '1' %}&uarr;
        {% elif order_by == 'leader' and reverse == '1' %}&darr;
        {% endif %}
      </a>
    </th>
    <th>Дії</th>
  </tr>
  </thead>
  {% endwith %}

  <tbody>
  {% for group in groups %}
  <tr>
    <td>{{ group.id }}</td>
    <td><a href="{% url 'students:groups_edit' group.id %}">{{ group.title }}</a></td>
    <td><a href="{% url 'students:students_edit' group.leader.id %}">{{ group.leader }}</a></td>
    <td>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Дія
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'students:groups_edit' group.id %}">Редагувати</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'students:groups_delete' group.id %}">Видалити</a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
<!-- End Groups List -->

{% if groups.has_other_pages %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" aria-label="Previous"
         href="?page=1&order_by={{ order_by }}&reverse={{ reverse }}">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for p in groups.paginator.page_range %}
    <li class="page-item {% if groups.number == p %}active{% endif %}">
      <a class="page-link"
         href="?page={{ p }}&order_by={{ order_by}}&reverse={{ reverse }}">{{ p }}</a>
    </li>
    {% endfor %}
    <li class="page-item">
      <a class="page-link" aria-label="Next"
         href="?page={{ groups.paginator.num_pages }}&order_by={{ order_by}}&reverse={{ reverse }}">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}

{% endblock content %}

students/templates/students/students_add.html
{% extends "students/base.html" %}
{% load static %}

{% block meta_title %}Додати Студента{% endblock meta_title %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-warning" role="alert">{{ message }}</div>
  {% endfor %}
{% endif %}

{% block title %}Додати Студента{% endblock title %}


{% block content %}
<form action="{% url 'students:students_add' %}"
      method="post"
      enctype="multipart/form-data">
  {% csrf_token %}

  <div>
    <label for="first_name">Імʼя*</label>
    <input id="first_name" type="text" value="{{ request.POST.first_name }}" name="first_name" placeholder="Введіть ваше імʼя"/>
    <span class="text-muted">{{errors.first_name}}</span>
  </div>
  <div>
    <label for="last_name">Прізвище*</label>
    <input id="last_name" type="text" value="{{ request.POST.last_name }}" name="last_name" placeholder="Введіть ваше прізвище"/>
    <span class="text-muted">{{errors.last_name}}</span>
  </div>
  <div>
    <label for="middle_name">По-батькові</label>
    <input id="middle_name" type="text" value="{{ request.POST.middle_name }}" name="middle_name" placeholder="Введіть ваше по-батькові"/>
  </div>
  <div>
    <label for="birthday">Дата Народження*</label>
    <input id="birthday" type="text" value="{{ request.POST.birthday }}" name="birthday" placeholder="Напр. 1984-12-30"/>
    <span class="text-muted">{{errors.birthday}}</span>
  </div>
  <div>
    <label for="photo">Фото</label>
    <input id="photo" type="file" accept=".jpg, .jpeg, .png" value="" name="photo"/>
    <span class="text-muted">{{errors.photo}}</span>
  </div>
  <div>
    <label for="ticket">Білет*</label>
    <input id="ticket" type="text" value="{{ request.POST.ticket }}" name="ticket" placeholder="Введіть номер білета"/>
    <span class="text-muted">{{errors.ticket}}</span>
  </div>
  <div>
    <label for="student_group">Група*</label>
    <select id="student_group" name="student_group">
      <option value="">Виберіть групу</option>
      {% for group in groups %}
      <option value="{{ group.id }}"
              {% if group.id == request.POST.student_group|add:0 %}selected="selected"{% endif %}>
        {{ group.title }}
      </option>
      {% endfor %}
    </select>
    <span class="text-muted">{{errors.student_group}}</span>
  </div>
  <div>
    <label for="notes">Додаткові Нотатки</label>
    <textarea id="notes" class="form-control" name="notes" placeholder="Додайте нотатки"></textarea>
  </div>
  <div>
    <input type="submit" value="Додати" name="add_button"/>
    <button type="submit" name="cancel_button">Скасувати</button>
  </div>

</form>
{% endblock content %}

students/templates/students/students_list.html
{% extends "students/base.html" %}
{% load static %}

{% block meta_title %}Студенти{% endblock meta_title %}

{% block title %}База Студентів{% endblock title %}

{% block button %}
<div class="ml-3">
  <a class="btn btn-primary" href="{% url 'students:students_add' %}" role="button">Додати Студента</a>
</div>
{% endblock button %}

{% block content %}
<!-- Start Student List -->
<table class="table table-hover table-striped">
  {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
  <thead>
  <tr>
    <th>
      <a href="?order_by=id{% if order_by == 'id' and reverse != '1' %}&reverse=1{% endif %}">
        №
        {% if order_by == 'id' and reverse != '1' %}&uarr;
        {% elif order_by == 'id' and reverse == '1' %}&darr;
        {% endif %}
      </a>
    </th>
    <th>Фото</th>
    <th>
      <a href="?order_by=last_name{% if order_by == 'last_name' and reverse != '1' %}&reverse=1{% endif %}">
        Прізвище
        {% if order_by == 'last_name' and reverse != '1' %}&uarr;
        {% elif order_by == 'last_name' and reverse == '1'%}&darr;
        {% endif %}
      </a>
    </th>
    <th>
      <a href="?order_by=first_name{% if order_by == 'first_name' and reverse != '1' %}&reverse=1{% endif %}">
        Ім’я
        {% if order_by == 'first_name' and reverse != '1' %}&uarr;
        {% elif order_by == 'first_name' and reverse == '1'%}&darr;
        {% endif %}
      </a>
    </th>
    <th>
      <a href="?order_by=ticket{% if order_by == 'ticket' and reverse != '1' %}&reverse=1{% endif %}">
        № Білету
        {% if order_by == 'ticket' and reverse != '1' %}&uarr;
        {% elif order_by == 'ticket' and reverse == '1'%}&darr;
        {% endif %}
      </a>
    </th>
    <th>Дія</th>
  </tr>
  </thead>
  {% endwith %}

  <tbody>
  {% for student in students %}
  <tr>
    <td>{{ student.id }}</td>
    <td>
      <img class="rounded-circle" height="35" width="35"
           src="{% if student.photo %}{{ student.photo.url }}{% else %}{% static 'img/no_user_img.png' %}{% endif %}"/>
    </td>
    <td><a href="{% url 'students:students_edit' student.id %}">{{ student.last_name }}</a></td>
    <td><a href="{% url 'students:students_edit' student.id %}">{{ student.first_name }}</a></td>
    <td>{{ student.ticket }}</td>
    <td>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Дія
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'students:students_edit' student.id %}">Редагувати</a>
          <a class="dropdown-item" href="{% url 'students:journal' %}">Відвідування</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'students:students_delete' student.id %}">Видалити</a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
<!-- End Student List -->

{% if students.has_other_pages %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item">
      <a class="page-link" aria-label="Previous"
         href="?page=1&order_by={{ order_by }}&reverse={{ reverse }}">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for p in students.paginator.page_range %}
    <li class="page-item {% if students.number == p %}active{% endif %}">
      <a class="page-link"
         href="?page={{ p }}&order_by={{ order_by}}&reverse={{ reverse }}">{{ p }}</a>
    </li>
    {% endfor %}
    <li class="page-item">
      <a class="page-link" aria-label="Next"
         href="?page={{ students.paginator.num_pages }}&order_by={{ order_by}}&reverse={{ reverse }}">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}

{% endblock content %}